### ISSUE TITLE
Cannot open shared object file error

### ISSUE THREAD

**Issue by sinak** [NTIA/gr-ltetrigger#3]
After installing, I get the following error when trying to run the example code

```
sina@ubuntu16:~/sdr/gr-ltetrigger/examples$ ./cell_search_file.py --help
Traceback (most recent call last):
  File "./cell_search_file.py", line 26, in <module>
    from ltetrigger import downlink_trigger_c, cellstore
  File "/usr/local/lib/python2.7/dist-packages/ltetrigger/__init__.py", line 28, in <module>
    from ltetrigger_swig import *
  File "/usr/local/lib/python2.7/dist-packages/ltetrigger/ltetrigger_swig.py", line 28, in <module>
    _ltetrigger_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/ltetrigger/ltetrigger_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_ltetrigger_swig', fp, pathname, description)
ImportError: libgnuradio-ltetrigger.so: cannot open shared object file: No such file or directory
```

**Comment by djanderson** [comment]
Did PR #4 fix this issue? If not you probably just need to `sudo ldconfig`.

**Comment by sinak** [comment]
#4 didn't but `sudo ldconfig` did. Would you like me to add that to #4?

**Comment by sinak** [comment]
Ah looks like it's been merged already. Happy to open another.

**Comment by djanderson** [comment]
Sure, that'd be great.

**Comment by sinak** [comment]
The other package I needed (on a fresh ubuntu install) to get everything working was fftw-dev. Going to add that as well :).
